### ISSUE TITLE
FANCY_REMEMBER_ALL_URLS option and performance over time

### ISSUE THREAD

**Issue by ograycode** [peterbe/django-fancy-cache#36]
Are there known limitations to this option? I had enabled it to give more visibility to our system and at about ~22,000 entries, the endpoints that were being tracked stopped being functional. Clearing the `fancy-urls` key solved the issue immediately.

```
In [1]: v = cache.get('fancy-urls')

In [2]: len(v.keys())
Out[2]: 22717
```

Above was the final count before deleting the key.

**Comment by YPCrumble** [comment]
@ograycode is the issue here that the `fancy-urls` contained URLs that had expired and therefore were no longer cached, but remained as part of `fancy-urls`? I.e., the `fancy-urls` dict got larger and larger over time if it wasn't periodically cleaned up?

**Comment by peterbe** [comment]
If I could rewrite this from scratch I wouldn't store all the URLs into one massive `dict` but instead, make each cache key prefixed and stored directly into the cache so that lookups are always `O(1)`. 
If Redis is your cache backend, and you need to find out all existing keys, I know it has a search function like `cache.keys("foo_*")`. Not sure if something similar exists for Memcache. But if you use Memcache and really have a need to find out what the keys were, perhaps it's time to switch to `django-redis`. After all, it has great features and [is plenty fast](https://www.peterbe.com/plog/fastest-cache-backend-possible-for-django). 

Another option, if you want to reset *all* "fancy URL" keys, one simple solution is to always use a prefix in `django.conf.settings` and to simply change that when you feel like resetting all existing keys.

**Comment by YPCrumble** [comment]
@peterbe I'm coming up against this too due to the default Memcached limit of 1MB. I like the idea of using the separate key for each line, but like you point out, Memcached doesn't have the search functionality for "searching" cache keys.

One option I can think of is to "shard" the fancy_cache URLs by x time period and only keep n periods of data. So if X is one day, and n is one week, we would have seven keys at any given time and would concatenate these seven into one dict that is the equivalent of the current implementation's dict. 

I've been testing #45 with success on my server and would love to incorporate a fix to this issue as well as I update that!

Thanks again for maintaining this library and all your help thinking through the issues :D.

**Comment by peterbe** [comment]
I'm sorry that I can't give this full attention. It is certainly weird that as of this change you're not able to use regular Memcache but have to reconfigure it for this "CAS" thing. 

Perhaps we can change tact a little and make it a config thing. 
I.e. "if you have a LOT of keys and still use Memcache, please consider setting this other setting and make sure your memcached server has CAS support (see this link here)"
Then, we wouldn't break the functionality for most people.

**Comment by peterbe** [comment]
> @peterbe great idea - would something like the following work?
> 
> ```
> FANCY_COMPRESS_REMEMBERED_URLS = False  # If True, compress REMEMBERED_URLS using zlib
> FANCY_MEMCACHED_USE_CAS = False  # If True, use CAS with Memcached.
> ```

Yes please!
