### ISSUE TITLE
Memcache is not reliable place for storing REMEMBERED_URLS dict

### ISSUE THREAD

**Issue by srgkm** [peterbe/django-fancy-cache#7]
In case of many requests REMEMBERED_URLS becomes inconsistent therefore find_urls works incorrectly.
We faced the problem when REMEMBERED_URLS doesn't contain keys of cached items and the only solution was to restart memcached.

**Comment by YPCrumble** [comment]
@peterbe thanks for maintaining django fancy cache! I'm using this in a growing application on production and believe I may be running into this issue. 

I have a few ideas about how to solve it:

- Using a celery task that limits to one worker at a time to set `REMEMBERED_URLS`, but that would require a task queue. 
- Use Memcached's compare-and-set which is available if the user uses `PylibMC` as their Memcached wrapper: https://sendapatch.se/projects/pylibmc/reference.html#pylibmc.Client.cas. 
- Store `REMEMBERED_URLS` in the database instead of in Memcached and update this using an atomic transaction though obviously it's more likely that this would get out of sync with Memcached in the event of something like `cache.clear()`.

My sense is that the best solution would be to use the db to store `REMEMBERED_URLS` - the current `REMEMBERED_URLS` is already out of sync with the actual cache in the event of a larger application. What do you think, and would you be open to a PR that shifts `REMEMBERED_URLS` to a `models.py` file? Or do you have another idea on how this might be achieved?
